sudo: true

language: python
python:
 - 2.7.11

language: node_js
node_js:
 - node

addons:
  apt:
    sources:
      - libsdl1.2debian
      - libfdt1
      - libpixman-1-0

before_install:
 - sudo pip install virtualenv
 - chmod +x ./travis/install
install: ./travis/install

before_script:
 - chmod +x ./travis/build
script: ./travis/build

env:
  global:
    - PEBBLE_TOOL=4.4.1

branches:
  only:
    - master
